### ISSUE TITLE
may be necessary to vendor protobuf :-/

### ISSUE THREAD

**Issue by bensigelman** [opentracing/basictracer-python#2]
This is really a `pip` bug, but the following stack trace came from a mature python+django installation that already used protobuf locked at 2.6.1... it did not play nice with the proto stuff in basictracer-py.

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/appenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/appenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/appenv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/appenv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/appenv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/appenv/REDACTED/settings.py", line 13, in <module>
    import lightstep.tracer
  File "/appenv/local/lib/python2.7/site-packages/lightstep/tracer.py", line 11, in <module>
    from basictracer import BasicTracer
  File "/appenv/local/lib/python2.7/site-packages/basictracer/__init__.py", line 3, in <module>
    from .tracer import BasicTracer
  File "/appenv/local/lib/python2.7/site-packages/basictracer/tracer.py", line 6, in <module>
    from .propagation import BinaryPropagator, TextPropagator
  File "/appenv/local/lib/python2.7/site-packages/basictracer/propagation.py", line 9, in <module>
    from .wire_pb2 import TracerState
  File "/appenv/local/lib/python2.7/site-packages/basictracer/wire_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\nwire.proto\x12\x13\x62\x61sictracer_go.wire\"\xc1\x01\n\x0bTracerState\x12\x10\n\x08trace_id\x18\x01 \x01(\x06\x12\x0f\n\x07span_id\x18\x02 \x01(\x06\x12\x0f\n\x07sampled\x18\x03 \x01(\x08\x12I\n\rbaggage_items\x18\x04 \x03(\x0b\x32\x32.basictracer_go.wire.TracerState.BaggageItemsEntry\x1a\x33\n\x11\x42\x61ggageItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x06Z\x04wireb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by bensigelman** [comment]
(cc @bg451)

**Comment by tovin07** [comment]
Besides, I wonder why we have to put `protobuf` as a mandatory requirement in this repo?
I think that it should be an optional requirement.

Reference: https://github.com/opentracing/basictracer-python/blob/master/setup.py#L24
